ALTER TABLE "assistant_conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assistant_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fichajes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "finances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hoopgrid_challenges" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hoopgrid_guesses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "initial_squads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lineups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "market_listings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "market_values" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "matches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "official_play_by_play" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "official_player_mappings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "official_shots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "official_team_mappings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "official_team_standings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "player_mappings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "player_round_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "player_seasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "players" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "playoff_predictions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "playoff_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "porras" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "seasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_meta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "team_seasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tournament_fixtures" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tournament_phases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tournament_standings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tournaments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "transfer_bids" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_biwenger_credentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_playoff_media" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_rounds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_seasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
REVOKE ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public FROM PUBLIC;
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
    REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
    REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
    REVOKE ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public FROM anon, authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON ROUTINES FROM anon, authenticated;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='postgres') THEN
      ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
      ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;
      ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON ROUTINES FROM anon, authenticated;
    END IF;
  END IF;
END $$;
