-- LOCAL REHEARSAL ONLY. Not registered in Drizzle and not deployable.
-- Run with psql ON_ERROR_STOP against the isolated season_audit database.
BEGIN;
DO $$
BEGIN
  IF current_database() <> 'season_audit' THEN
    RAISE EXCEPTION 'This rehearsal requires season_audit';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM seasons WHERE id='2025-26' AND status='frozen') THEN
    RAISE EXCEPTION 'Audited frozen season missing';
  END IF;
END $$;

ALTER TABLE player_seasons ADD COLUMN IF NOT EXISTS position text;
ALTER TABLE player_seasons ADD COLUMN IF NOT EXISTS dorsal text;
ALTER TABLE player_seasons ADD COLUMN IF NOT EXISTS roster_snapshot_source text;

-- Observations from the preserved snapshot, not claimed historical effective dates.
UPDATE player_seasons ps
SET position=p.position, dorsal=p.dorsal,
    roster_snapshot_source='legacy_snapshot_2025_26'
FROM players p
WHERE ps.player_id=p.id AND ps.season_id='2025-26'
  AND ps.position IS NULL AND ps.dorsal IS NULL
  AND ps.roster_snapshot_source IS NULL;

CREATE TABLE IF NOT EXISTS team_seasons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id text NOT NULL REFERENCES seasons(id),
  team_id integer NOT NULL REFERENCES teams(id),
  name text,
  short_name text,
  img text,
  city text,
  arena_name text,
  latitude double precision,
  longitude double precision,
  snapshot_source text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (season_id,team_id)
);
ALTER TABLE team_seasons ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON team_seasons FROM PUBLIC;

INSERT INTO team_seasons
  (season_id,team_id,name,short_name,img,city,arena_name,latitude,longitude,snapshot_source)
SELECT '2025-26',t.id,t.name,t.short_name,t.img,t.city,t.arena_name,t.latitude,t.longitude,
       'legacy_snapshot_2025_26'
FROM teams t
WHERE EXISTS (
  SELECT 1 FROM matches m WHERE m.season_id='2025-26'
    AND (m.home_id=t.id OR m.away_id=t.id)
)
ON CONFLICT (season_id,team_id) DO NOTHING;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM player_seasons ps JOIN players p ON p.id=ps.player_id
    WHERE ps.season_id='2025-26'
      AND (ps.position IS DISTINCT FROM p.position OR ps.dorsal IS DISTINCT FROM p.dorsal)
  ) THEN RAISE EXCEPTION 'Roster snapshot mismatch'; END IF;
  IF EXISTS (
    SELECT 1 FROM matches m WHERE m.season_id='2025-26'
    AND (NOT EXISTS (SELECT 1 FROM team_seasons t WHERE t.season_id=m.season_id AND t.team_id=m.home_id)
      OR NOT EXISTS (SELECT 1 FROM team_seasons t WHERE t.season_id=m.season_id AND t.team_id=m.away_id))
  ) THEN RAISE EXCEPTION 'Season team coverage mismatch'; END IF;
END $$;
COMMIT;
