import 'server-only';
import {
  fetchStreakStats,
  fetchHeatCheckStats,
  fetchHunterStats,
  fetchBottlerStats,
  fetchHeartbreakerStats,
  fetchNoGloryStats,
  fetchJinxStats,
  fetchFloorCeilingStats,
  fetchVolatilityStats,
  fetchEfficiencyStats,
  fetchDominanceStats,
  fetchReliabilityStats,
  fetchTheoreticalGapStats,
  fetchRivalryMatrixStats,
  fetchLeagueComparisonStats,
} from '@/features/standings/server';
import {
  getManagerMarketStats,
  getBestSeller,
  getBiddingDuelsStats,
  getTheThief,
} from '@/features/market/server';
import type { CompareAdvancedStats } from '../../models/compare';

const defaultDependencies = {
  fetchStreakStats,
  fetchHeatCheckStats,
  fetchHunterStats,
  fetchBottlerStats,
  fetchHeartbreakerStats,
  fetchNoGloryStats,
  fetchJinxStats,
  fetchFloorCeilingStats,
  fetchVolatilityStats,
  fetchEfficiencyStats,
  fetchDominanceStats,
  fetchReliabilityStats,
  fetchTheoreticalGapStats,
  fetchRivalryMatrixStats,
  fetchLeagueComparisonStats,
  getManagerMarketStats,
  getBestSeller,
  getBiddingDuelsStats,
  getTheThief,
};
export function createCompareAdvancedService(deps = defaultDependencies) {
  return async function getCompareAdvancedData(): Promise<CompareAdvancedStats> {
    const [
      streaks,
      heatCheck,
      hunter,
      bottler,
      heartbreaker,
      noGlory,
      jinx,
      floorCeiling,
      volatility,
      efficiency,
      dominance,
      reliability,
      theoreticalGap,
      rivalryMatrix,
      leagueComparison,
      market,
      bestSeller,
      biddingDuels,
      theThief,
    ] = await Promise.all([
      deps.fetchStreakStats(),
      deps.fetchHeatCheckStats(),
      deps.fetchHunterStats(),
      deps.fetchBottlerStats(),
      deps.fetchHeartbreakerStats(),
      deps.fetchNoGloryStats(),
      deps.fetchJinxStats(),
      deps.fetchFloorCeilingStats(),
      deps.fetchVolatilityStats(),
      deps.fetchEfficiencyStats(),
      deps.fetchDominanceStats(),
      deps.fetchReliabilityStats(),
      deps.fetchTheoreticalGapStats(),
      deps.fetchRivalryMatrixStats(),
      deps.fetchLeagueComparisonStats(),
      deps.getManagerMarketStats(),
      deps.getBestSeller(),
      deps.getBiddingDuelsStats(),
      deps.getTheThief(),
    ]);
    return {
      streaks: streaks || [],
      heatCheck: heatCheck || [],
      hunter: hunter || [],
      bottler: bottler || [],
      heartbreaker: heartbreaker || [],
      noGlory: noGlory || [],
      jinx: jinx || [],
      floorCeiling: floorCeiling || [],
      volatility: volatility || [],
      efficiency: efficiency || [],
      dominance: dominance || [],
      reliability: reliability || [],
      theoreticalGap: theoreticalGap || [],
      rivalryMatrix: rivalryMatrix?.matrix || {},
      leagueComparison: leagueComparison || [],
      market: market || [],
      bestSeller: bestSeller || [],
      biddingDuels: biddingDuels || { matrix: {}, summaries: [] },
      theThief: theThief || [],
    };
  };
}
export const getCompareAdvancedData = createCompareAdvancedService();
