/** Temporary compatibility exports for unmigrated callers. No Market query implementation remains here. */
export type { CurrentMarketListing } from '@/features/market/public';
export type { RecentTransfer } from '@/features/market/public';
export type { MarketActivityTrend as MarketTrend } from '@/features/market/public';
export type { MarketOpportunity } from '@/features/market/public';
export type { PriceChange } from '@/features/market/public';
export type { MarketActivityKPIs as MarketKPIs } from '@/features/market/public';
export type { MarketOverviewKPIs } from '@/features/market/public';
export type { TopTransferredPlayer } from '@/features/market/public';
export type { EnrichedTransfer } from '@/features/market/public';
export type { BigSpender } from '@/features/market/public';
export type { RecordBid } from '@/features/market/public';
export type { MarketTrendDay as MarketAnalysisDay } from '@/features/market/public';
export type { PositionAnalysis } from '@/features/market/public';
export type { MarketTransferPage as PaginatedTransfers } from '@/features/market/public';
export type { ManagerMarketStats } from '@/features/market/public';
export type { BestSeller } from '@/features/market/public';
export type { BestRevaluation } from '@/features/market/public';
export type { BestValuePlayer } from '@/features/market/public';
export type { MarketValueDetail as BestValueDetail } from '@/features/market/public';
export type { TheThief } from '@/features/market/public';
export type { BiggestSteal } from '@/features/market/public';
export type { TheVictim } from '@/features/market/public';
export type { OverpayerManager } from '@/features/market/public';
export type { InflatedPlayer } from '@/features/market/public';
export type { InfirmaryPlayer } from '@/features/market/public';
export type { BidDuelUser } from '@/features/market/public';
export type { BidDuelRecord } from '@/features/market/public';
export type { BidDuelSummary } from '@/features/market/public';
export type { BiddingDuelsStats } from '@/features/market/public';
export type { MarketDuelDetail as BidDuelDetail } from '@/features/market/public';
export type { SingleFlip } from '@/features/market/public';
export type { PercentageGain } from '@/features/market/public';
export type { MostOwnersPlayer } from '@/features/market/public';
export type { MissedOpportunity } from '@/features/market/public';
export type { TopTrader } from '@/features/market/public';
export type { QuickFlip } from '@/features/market/public';
export type { LongHold } from '@/features/market/public';
export type { Devaluation } from '@/features/market/public';
export { getAllTransfers } from '@/features/market/server';
export { getRecentTransfers } from '@/features/market/server';
export { getMarketTrends } from '@/features/market/server';
export { getMarketOpportunities } from '@/features/market/server';
export { getSignificantPriceChanges } from '@/features/market/server';
export { getMarketKPIs } from '@/features/market/server';
export { getMarketOverviewKPIs } from '@/features/market/server';
export { getTopTransferredPlayer } from '@/features/market/server';
export { getRecordTransfer } from '@/features/market/server';
export { getBigSpender } from '@/features/market/server';
export { getRecordBid } from '@/features/market/server';
export { getMarketTrendsAnalysis } from '@/features/market/server';
export { getPositionAnalysis } from '@/features/market/server';
export { getLiveMarketTransfers } from '@/features/market/server';
export { getManagerMarketStats } from '@/features/market/server';
export { getBestSeller } from '@/features/market/server';
export { getBestRevaluation } from '@/features/market/server';
export { getBestValuePlayer } from '@/features/market/server';
export { getBestValueDetails } from '@/features/market/server';
export { getInfirmaryPlayers } from '@/features/market/server';
export { getTheThief } from '@/features/market/server';
export { getBiggestSteal } from '@/features/market/server';
export { getTheVictim } from '@/features/market/server';
export { getOverpayerManager } from '@/features/market/server';
export { getInflatedPlayer } from '@/features/market/server';
export { getBiddingDuelsStats } from '@/features/market/server';
export { getBiddingDuelDetails } from '@/features/market/server';
export { getBestSingleFlip } from '@/features/market/server';
export { getWorstSingleFlip } from '@/features/market/server';
export { getBestPercentageGain } from '@/features/market/server';
export { getMostOwnersPlayer } from '@/features/market/server';
export { getMissedOpportunity } from '@/features/market/server';
export { getTopTrader } from '@/features/market/server';
export { getProfitablePlayer } from '@/features/market/server';
export { getLossyPlayer } from '@/features/market/server';
export { getQuickestFlip } from '@/features/market/server';
export { getLongestProfitableHold } from '@/features/market/server';
export { getWorstRevaluation } from '@/features/market/server';
export { getCurrentMarketListings } from '@/features/market/server';
export type {
  MarketActivityTransfer as Transfer,
  PlayerProfitability,
} from '@/features/market/public';
